#!/usr/bin/env python
#-*- coding: utf8 -*-

FRAMES = 30
MOVE_SPEED = 3
BULLET_SPEED = 8

DIRECTION_NONE  = -1
DIRECTION_DOWN  = 1
DIRECTION_LEFT  = 2
DIRECTION_UP    = 4
DIRECTION_RIGHT = 8

AXIS_X = 0
AXIS_Y = 1

#BACKGROUND_COLOUR = (46,52,54)
BACKGROUND_COLOUR = (0, 0, 0)

MAPS_DIR = 'data/maps'
SOUNDS_DIR = 'data/sounds'
TEXTURES_DIR = 'data/textures'

JOY_CENTERED = (0, 0)
JOY_UP       = (0, 1)
JOY_DOWN     = (0, -1)
JOY_RIGHT    = (1, 0)
JOY_LEFT     = (-1, 0)


EVENT_FIRE = 0
EVENT_MOVE_LEFT = 1
EVENT_MOVE_RIGHT = 2
EVENT_MOVE_UP = 3
EVENT_MOVE_DOWN = 4
EVENT_STOP = 5

GAME_CONTINUE = 0
GAME_OVER = -1
